services:
  postgres:
    image: postgres:16.0
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: